/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function perform(pattern: FeedbackPattern, performanceTime: PerformanceTime): void
export const enum PerformanceTime {
  Default = 0,
  Now = 1,
  DrawCompleted = 2
}
export const enum FeedbackPattern {
  Generic = 0,
  Alignment = 1,
  LevelChange = 2
}
