/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * WARNING: This uses an undocumented internal MacOS API, and might break at any time
 * or cause your App to be rejected from the Mac App Store.
 *
 * You do get way deeper clicks though :D
*/
export function internalApiPerform(actuation: Actuation): void
/**
 * WARNING WARNING WARNING WARNING WARNING
 * WARNING WARNING WARNING WARNING WARNING
 *
 * THIS IS AN UNSAFE RUST FUNCTION
 * THIS CAN SEGFAULT
 * CALL AT YOUR OWN RISK
 *
 * WARNING WARNING WARNING WARNING WARNING
 * WARNING WARNING WARNING WARNING WARNING
 *
 * This uses an undocumented internal MacOS API, and might break at any time
 * or cause your App to be rejected from the Mac App Store.
 *
 * You do get way deeper clicks though :D
*/
export function unsafeInternalApiPerform(actuation: number, unknown1: number, unknown2: number, unknown3: number): void
export const enum Actuation {
  None = 0,
  Weak = 3,
  Medium = 4,
  Strong = 6,
  One = 1,
  Two = 2,
  Fifteen = 15,
  Sixteen = 16
}
export function perform(pattern: FeedbackPattern, performanceTime: PerformanceTime): void
export const enum PerformanceTime {
  Default = 0,
  Now = 1,
  DrawCompleted = 2
}
export const enum FeedbackPattern {
  Generic = 0,
  Alignment = 1,
  LevelChange = 2
}
